version: '3.4'

services:
  koel:
    image: nairvish/docker-koel
    container_name: "koel_base"
    restart: always
    depends_on:
      - database
    ports:
      - 3006:80
    environment:
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_USERNAME: koel
      DB_PASSWORD: koel
      DB_DATABASE: koel
      IGNORE_DOT_FILES: 'true'
      APP_ENV: production
      APP_DEBUG: 'true'
      APP_URL: http://koel.mater.io
      APP_MAX_SCAN_TIME: 600
      MEMORY_LIMIT: 2048
      STREAMING_METHOD: php
      FFMPEG_PATH: /usr/local/bin/ffmpeg
      OUTPUT_BIT_RATE: 256
      ALLOW_DOWNLOAD: 'true'
      CACHE_MEDIA: 'true'
      APP_LOG_LEVEL: debug
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      SESSION_DRIVER: file
      QUEUE_DRIVER: sync
      MAIL_DRIVER: smtp
      MAIL_HOST: smtp.qq.com
      MAIL_PORT: 587
      MAIL_USERNAME: materliu
      MAIL_PASSWORD: 123
      MAIL_ENCRYPTION: tls
      ## LAST.FM config ##
      # LASTFM_API_KEY=
      # LASTFM_API_SECRET=
      ## YOUTUBE config ##
      # YOUTUBE_API_KEY=
      ## PUSHER config ##
      # PUSHER_APP_ID=
      # PUSHER_APP_KEY=
      # PUSHER_APP_SECRET=
      # PUSHER_APP_CLUSTER=
    volumes:
      - /Users/liujuguang/Workspaces/music:/music
      - /Users/liujuguang/Workspaces/music/covers:/var/www/html/public/img/covers

  database:
    image: mysql/mysql-server:5.7
    container_name: "koel_mysql"
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: koel
      MYSQL_USER: koel
      MYSQL_PASSWORD: koel

  dbviewer:
    image: phpmyadmin
    container_name: koel_db_viewer  
    links:
      - database
    restart: always
    ports:
      - 10083:80
    environment:
      - PMA_HOST=database
      - PMA_USER=koel
      - PMA_PASSWORD=koel

volumes:
  db:
    driver: local
  music:
    driver: local
  covers:
    driver: local